### ISSUE TITLE
Implement Scoring

### ISSUE THREAD

**Issue by jacobsax** [TeamFarce/Lorem-Ipsum#2]
Implement an Incremented Scoring System

**Comment by Comprs** [comment]
The scoring system, as per the requirements, will use the following parameters to calculate the score:
- [ ] Time Taken
- [ ] Incorrect Accusations
- [ ] Questions Asked
- [ ] Clues Found

All of these parameters are obvious if they should contribute positively or negatively, with the exception of "Questions Asked". What is everyone's opinion on this matter?
